# Generated by Django 4.2.1 on 2023-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='bu terminaldan test 1'),
            preserve_default=False,
        ),
    ]
